project:
  type: website

website:
  open-graph: true
  favicon: images/logo_fav.jpg
  title: "Slam Dunk"
  navbar:
    left:
      - about.qmd
      - subscribe.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

