project:
  type: website

website:
  favicon: images/logo_fav.jpg
  google-analytics: "G-66MCY7L0V7"
  image: images/logo_fav.jpg
  navbar:
    left:
      - subscribe.qmd
      - blog.qmd
      - faq.qmd
      - contact.qmd
    search: false
    tools:
      - icon: discord
        href: https://whop.com/slam-dunk-bets/
      - icon: twitter
        href: https://x.com/slam_dunk_bets
      - icon: envelope
        href: "mailto:slamdunkbettingservices@gmail.com"
  open-graph: true
  page-footer: 
    border: false
    center: |
      21+ Only | [National Problem Gambling Helpline](https://www.ncpgambling.org/help-treatment/about-the-national-problem-gambling-helpline/) <br>
      © Slam Dunk Betting Services LLC, 2024
  search: false
  title: "Slam Dunk Bets"
  twitter-card:
    creator: "@jimtheflash"
    site: "@slam_dunk_bets"

format:
  html:
    theme: litera
    css: styles.css

editor: visual

