project:
  type: website

website:
  favicon: images/logo_fav.jpg
  navbar:
    left:
      - subscribe.qmd
      - about.qmd
    logo: images/logo_fav.jpg
    title: false
  open-graph: true
  title: "Slam Dunk"
  twitter-card:
    creator: "@jimtheflash"
    site: "@slam_dunk_bets"

format:
  html:
    theme: litera
    css: styles.css

editor: visual

