project:
  type: website

website:
  open-graph: true
  favicon: images/logo_fav.jpg
  title: "Slam Dunk"
  navbar:
    left:
      - subscribe.qmd
      - about.qmd
format:
  html:
    theme: litera
    css: styles.css

editor: visual

