project:
  type: website
  resources:
    - images/hof-carousel/**
    - scripts/hof-carousel.js
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  favicon: images/brand/favicon-32.svg
  google-analytics: "G-66MCY7L0V7"
  navbar:
    left:
      - text: "Subscribe"
        href: subscribe.qmd
      - text: "Apps"
        href: apps.qmd
      - text: "Data"
        href: data.qmd
      - text: "Articles"
        href: articles.qmd
      - text: "FAQ"
        href: faq.qmd
      - text: "Contact"
        href: contact.qmd
    search: false
    tools:
      - icon: twitter
        href: https://x.com/jimtheflash
      - icon: envelope
        href: "mailto:slamdunkbettingservices@gmail.com"
      - icon: discord
        href: https://sharpduel.com/slam_dunk_bets
  open-graph: true
  page-footer: 
    border: false
    center: |
      21+ Only | [National Problem Gambling Helpline](https://www.ncpgambling.org/help-treatment/about-the-national-problem-gambling-helpline/) <br>
      © Slam Dunk Betting Services LLC, 2026
  search: false
  title: "Slam Dunk Bets"
  twitter-card:
    creator: "@jimtheflash"
    site: "@jimtheflash"

format:
  html:
    theme: [litera, custom.scss]
    css: styles.css
    anchor-sections: false

editor: visual
