---
title: "Our Top ROI 2024 WNBA Players"
subtitle: "I Got A Fever!"
author: Slam Dunk Bets
date: 2024-10-07
categories: [] # self-defined categories
draft: true
---

We're in the last week of the 2024 WNBA season, which is a good time for recaps. Here are our top ROI players from this season.

-   Kelsey Mitchell, Indiana Fever

    -   66 bets, 28 wins, net 81 units, 212% ROI

    -   The only player we hit an exact method first basket this season, but WOW did we hit a bunch of them

-   Odyssey Sims

    -   53 bets, 12 wins, net 62 units, 155% ROI

    -   Started in Dallas and ended in LA, Sims

-   Rae Burrell

    -   21 bets, 7 wins, net 49 units, 205% ROI

    -   Back to back Sparks guards on the list, RB only started the last 7 games of the year but managed to hit multiple first basket and first basket by team plays

-   Julie Vanloo

    -   49 bets, 9 wins, net 47 units, 135% ROI

    -   

-   Maya Caldwell

    -   22 bets, 5 wins, net 44 units, 166% ROI

    -   

-   Betnijah Laney-Hamilton

    -   33 bets, 6 wins, net 43 units, 150% ROI

-   Bridget Carleton

    -   17 bets, 6 wins, net 42 units, 326% ROI

    -   Second highest ROI %

-   Brittney Sykes

    -   4 bets, 3 wins, net 35 units, 712% ROI

    -   Our highest ROI % by a wide margin, and highest win rate as well (75%)
